name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env: DATABASE_URL=postgresql://postgres.zkqrczoxjeagtrbudwla:ldukUtHDAVySfRWT@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # RAILS_ENV: test
      # DATABASE_URL: postgres://postgres:password@localhost:5432/academy_quest_test
      DATABASE_URL=postgresql://postgres.zkqrczoxjeagtrbudwla:ldukUtHDAVySfRWT@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          bin/rails db:create db:schema:load

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Run Cucumber tests
        run: bundle exec cucumber
